#!/usr/bin/env python
# snrandom

import os
import random
import string

if __name__ == '__main__':
    # specify the directory containing the files and list of them
    directory = os.getcwd()
    files = os.listdir(directory)
    try:
        files.remove('.DS_Store')
    except:
        pass

    # shuffle the list of files randomly and define basename and indexing width
    random.shuffle(files)

    # define basename and indexing width
    characters = string.ascii_letters + string.digits
    base_name = ''.join(random.choice(characters) for _ in range(8)) + '.'
    zfill = len(str(len(files)))

    # iterate through the shuffled files and rename them
    for ind, file_name in enumerate(files, start=1):
        # get the file extension
        file_extension = os.path.splitext(file_name)[1]
        
        # create the new file name with an index
        ind_str = str(ind).zfill(zfill)
        new_name = base_name + ind_str + file_extension
        
        # construct the full paths for the old and new names
        old_path = os.path.join(directory, file_name)
        new_path = os.path.join(directory, new_name)
        
        # rename the file
        os.rename(old_path, new_path)
    
    print("files renamed successfully.")
